name: custom_gallery_display
description: Customization of the gallery display or even camera and video.
version: 0.3.8
homepage: https://github.com/AhmedAbdoElhawary/custom_gallery_display.git

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  photo_manager: ^2.1.4
  shimmer: ^2.0.0
  image_crop: ^0.4.1
  camera: ^0.10.0
  image: ^3.2.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
