name: image_picker_plus
description: Customization of the gallery display or even camera and video.
version: 0.5.9
homepage: https://github.com/AhmedAbdoElhawary/image_picker_plus.git

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  photo_manager: ^3.6.3
  shimmer: ^3.0.0
  camera: ^0.11.0+2
  image: ^4.5.2
  video_player: ^2.9.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

#flutter:
