name: image_picker_plus
description: Customization of the gallery display or even camera and video.
version: 0.5.3
homepage: https://github.com/AhmedAbdoElhawary/image_picker_plus.git

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  photo_manager: ^2.2.1
  shimmer: ^2.0.0
  image_crop: ^0.4.1
  camera: ^0.10.0+1
  image: ^3.2.0
  video_player: ^2.4.5
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
