name: image_picker_plus
description: Customization of the gallery display or even camera and video.
version: 0.5.10
homepage: https://github.com/AhmedAbdoElhawary/image_picker_plus.git

environment:
  sdk: '>=2.17.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  photo_manager: ^3.8.3
  shimmer: ^3.0.0
  camera: ^0.11.4
  image: ^4.8.0
  video_player: ^2.11.0
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.lykhonis.imagecrop
        pluginClass: ImageCropPlugin
      ios:
        pluginClass: ImageCropPlugin
